import { Router, type Request, type Response } from 'express'
import { srsService, type GeneratedSRS } from '../services/srsService'

const router = Router()
const documentStore = new Map<string, GeneratedSRS>()

// ─── Markdown export helper ───────────────────────────────────────────────────

function toMarkdown(document: GeneratedSRS): string {
  const lines: string[] = []
  const d = document.document

  lines.push('# Software Requirements Specification')
  lines.push(`## ${document.repoName}`)
  lines.push(`**Version:** ${document.version} | **Date:** ${new Date(document.generatedAt).toLocaleString()} | **Generated by:** NDEX AI`)
  lines.push('')
  lines.push('---')
  lines.push('')
  lines.push('## Table of Contents')
  lines.push('1. Introduction')
  lines.push('2. Overall Description')
  lines.push('3. Functional Requirements')
  lines.push('4. Non-Functional Requirements')
  lines.push('5. System Architecture')
  lines.push('6. Data Models')
  lines.push('7. API Endpoints')
  lines.push('8. Testing Requirements')
  lines.push('9. Glossary')
  lines.push('')

  lines.push('## 1. Introduction')
  lines.push('### 1.1 Purpose')
  lines.push(d.introduction.purpose)
  lines.push('')
  lines.push('### 1.2 Scope')
  lines.push(d.introduction.scope)
  lines.push('')
  lines.push('### 1.3 Overview')
  lines.push(d.introduction.overview)
  lines.push('')

  lines.push('## 2. Overall Description')
  lines.push('### 2.1 Product Perspective')
  lines.push(d.overallDescription.productPerspective)
  lines.push('')
  lines.push('### 2.2 Product Functions')
  d.overallDescription.productFunctions.forEach(item => lines.push(`- ${item}`))
  lines.push('')

  lines.push('## 3. Functional Requirements')
  d.functionalRequirements.forEach(fr => {
    lines.push(`### ${fr.id}: ${fr.title}`)
    lines.push(`**Priority:** ${fr.priority}`)
    lines.push(`**Description:** ${fr.description}`)
    lines.push(`**Inputs:** ${fr.inputs.join(', ') || 'None'}`)
    lines.push(`**Outputs:** ${fr.outputs.join(', ') || 'None'}`)
    lines.push(`**Dependencies:** ${fr.dependencies.join(', ') || 'None'}`)
    lines.push('')
  })

  lines.push('## 4. Non-Functional Requirements')
  d.nonFunctionalRequirements.forEach(nfr => {
    lines.push(`### ${nfr.id} (${nfr.category})`)
    lines.push(`**Description:** ${nfr.description}`)
    lines.push(`**Metric:** ${nfr.metric}`)
    lines.push(`**Rationale:** ${nfr.rationale}`)
    lines.push('')
  })

  lines.push('## 5. System Architecture')
  lines.push(d.systemArchitecture.description)
  lines.push('')

  lines.push('## 6. Data Models')
  d.dataModels.forEach(model => {
    lines.push(`### ${model.name}`)
    lines.push(model.description)
    model.fields.forEach(field => {
      lines.push(`- ${field.name} (${field.type}) required=${field.required}: ${field.description}`)
    })
    lines.push('')
  })

  lines.push('## 7. API Endpoints')
  d.apiEndpoints.forEach(ep => {
    lines.push(`- **${ep.method} ${ep.path}**: ${ep.description}`)
  })
  lines.push('')

  lines.push('## 8. Testing Requirements')
  lines.push(`- Unit Testing: ${d.testingRequirements.unitTesting}`)
  lines.push(`- Integration Testing: ${d.testingRequirements.integrationTesting}`)
  lines.push(`- E2E Testing: ${d.testingRequirements.e2eTesting}`)
  lines.push(`- Performance Testing: ${d.testingRequirements.performanceTesting}`)
  lines.push('')

  lines.push('## 9. Glossary')
  d.glossary.forEach(item => {
    lines.push(`- **${item.term}**: ${item.definition}`)
  })

  return lines.join('\n')
}

// ─── Routes ───────────────────────────────────────────────────────────────────

// GET /api/srs/generate?owner=&repo=  (EventSource-compatible SSE stream)
router.get('/generate', async (req: Request, res: Response) => {
  const owner = typeof req.query.owner === 'string' ? req.query.owner.trim() : ''
  const repo  = typeof req.query.repo  === 'string' ? req.query.repo.trim()  : ''

  if (!owner || !repo) {
    res.status(400).json({ error: 'owner and repo query params are required' })
    return
  }

  res.setHeader('Content-Type', 'text/event-stream')
  res.setHeader('Cache-Control', 'no-cache, no-transform')
  res.setHeader('Connection', 'keep-alive')
  res.setHeader('Access-Control-Allow-Origin', '*')
  res.flushHeaders()

  const send = (payload: Record<string, unknown>): void => {
    res.write(`data: ${JSON.stringify(payload)}\n\n:\n\n`)
    if (typeof (res as unknown as { flush?: () => void }).flush === 'function') {
      (res as unknown as { flush: () => void }).flush()
    }
  }

  try {
    const document = await srsService.generateSRS(owner, repo, (step, progress, label) => {
      send({ step, progress, label })
    })

    documentStore.set(document.id, document)

    send({
      step: 'complete',
      progress: 100,
      label: document.metadata.generationMode === 'fallback' ? 'Fallback SRS generated.' : 'SRS generated successfully!',
      document,
      mode: document.metadata.generationMode,
      warning: document.metadata.warning,
    })
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Failed to generate SRS'
    send({ step: 'error', progress: 100, label: message, error: message })
  } finally {
    res.end()
  }
})

// GET /api/srs/:id  — retrieve stored doc
router.get('/:id', (req: Request, res: Response) => {
  const document = documentStore.get(req.params.id)
  if (!document) {
    res.status(404).json({ error: 'SRS document not found' })
    return
  }
  res.json(document)
})

// POST /api/srs/:id/export/markdown
router.post('/:id/export/markdown', (req: Request, res: Response) => {
  const document = documentStore.get(req.params.id)
  if (!document) {
    res.status(404).json({ error: 'SRS document not found' })
    return
  }

  const markdown = toMarkdown(document)
  const fileName = `${document.repoName.replace('/', '-')}-SRS-v${document.version}.md`

  res.setHeader('Content-Type', 'text/markdown; charset=utf-8')
  res.setHeader('Content-Disposition', `attachment; filename="${fileName}"`)
  res.send(markdown)
})

export default router
